root = "."
tmp_dir = "/tmp"

[build]
	bin = "./dist/server"
  cmd = "make build"
  delay = 1000
	exclude_dir = ["api", "dist"]
  include_ext = ["go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
